# @package _global_
run_name: run15
notes: run6と同じdatasetでnegative_size=1, epoch=20で実験
use_fold: 0

negative_size: 1
use_mask_pad_token: true
retrieval_model:
  name: Qwen/Qwen2.5-14B-Instruct
  use_lora: true
  is_quantized: true
  use_sentence_transformers: false
  lora:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05
    task_type: FEATURE_EXTRACTION

trainer:
  epoch: 20
  batch_size: 16
  learning_rate: 1e-4
  weight_decay: 0.01
