# @package _global_
run_name: run2
use_fold: 0

retrieval_model:
  name: Alibaba-NLP/gte-Qwen2-7B-instruct
  use_lora: false
  is_quantized: false
  use_sentence_transformers: false  # こっちだとスコアマシになるがfalseだとスコア悪くなる
  lora:
    r: 8
    lora_alpha: 16
trainer:
  batch_size: 32
