# @package _global_
run_name: run4
notes: これは他のモデルか何かに上書きする
use_fold: 0

retrieval_model:
  name: nvidia/NV-Embed-v2
  use_lora: false
  is_quantized: true
  use_sentence_transformers: false
  lora:
    r: 64
    lora_alpha: 256
trainer:
  batch_size: 32
