# @package _global_
run_name: run5
notes: nvidiaモデルをリベンジ
use_fold: 0


retrieval_model:
  name: nvidia/NV-Embed-v2
  use_lora: true
  is_quantized: true
  lora:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05

max_candidates: 100
negative_size: 3

trainer:
  epoch: 10
  batch_size: 4
  gradient_accumulation_steps: 16
  gradient_checkpointing: false  # nvidia-emb-v2は対応していないらしい
