# @package _global_
run_name: run5
use_fold: 0

retrieval_model:
  name: zeta-alpha-ai/Zeta-Alpha-E5-Mistral
  use_lora: false
  is_quantized: true
  use_sentence_transformers: false
  lora:
    r: 64
    lora_alpha: 256
trainer:
  batch_size: 32
