# @package _global_
run_name: sub1
phase: test
max_candidates: ${retrieve_num}

retrieval_model:
  name: Qwen/Qwen2.5-Math-7B-Instruct
  names:
    - ${path.model_dir}/${exp_name}/run6
    - ${path.model_dir}/${exp_name}/run18
    - ${path.model_dir}/${exp_name}/run23
  weights:
    - 2
    - 1
    - 2
  use_lora: true
  is_quantized: true
  use_sentence_transformers: false
  lora:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05
    task_type: FEATURE_EXTRACTION
  batch_size: 16


llm_model:
  use: true
  predict_type: reranking
