# @package _global_
run_name: run0
notes: "nvidia modelを試す"
use_fold: 0

retrieval_model:
  name: nvidia/NV-Embed-v2
  use_lora: true
  lora:
    r: 64
    lora_alpha: 256

max_candidates: 50
negative_size: 10
trainer:
  epoch: 2
  batch_size: 2
  gradient_accumulation_steps: 1
  gradient_checkpointing: false
  learning_rate: 8e-6
