# @package _global_
run_name: eval0
use_fold: 0

retrieval_model:
  name: dunzhang/stella_en_1.5B_v5
  names:
    - ${path.model_dir}/${exp_name}/run0_dunzhang-stella_en_1.5B_v5_top${max_candidates}_rank${retrieval_model.lora.r}_batch${trainer.batch_size}
  lora:
    r: 8
  max_length: 1024

max_candidates: 100

trainer:
  epoch: 1
  batch_size: 64
