# @package _global_
run_name: run4_dunzhang-stella_en_1.5B_v5_top${max_candidates}_rank${retrieval_model.lora.r}_batch${trainer.batch_size}_alpha${retrieval_model.lora.lora_alpha}
use_fold: 0

retrieval_model:
  name: dunzhang/stella_en_1.5B_v5
  lora:
    r: 64
    lora_alpha: 64

max_candidates: 25

trainer:
  epoch: 1
  batch_size: 64
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
