# @package _global_
run_name: run0
notes: "mask pad tokenで過学習防ぐ"


retrieval_model:
  name: dunzhang/stella_en_1.5B_v5
  use_lora: true

max_candidates: 50
negative_size: 10
trainer:
  epoch: 10
  batch_size: 64
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  learning_rate: 8e-6
