# @package _global_
run_name: run2
notes: nvidia model"


retrieval_model:
  name: nvidia/NV-Embed-v2
  use_lora: true

max_candidates: 50
negative_size: 10

trainer:
  epoch: 5
  batch_size: 1
  gradient_accumulation_steps: 64
  gradient_checkpointing: false
  learning_rate: 8e-6
