# @package _global_
run_name: run0_dunzhang-stella_en_1.5B_v5_epoch${trainer.epoch}
use_fold: 0

retrieval_model:
  name: dunzhang/stella_en_1.5B_v5
  lora:
    r: 64

max_candidates: 25

trainer:
  epoch: 10
  batch_size: 64
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
