# @package _global_
run_name: run0_nvidia-NV-Embed-v2-top${max_candidates}_rank${retrieval_model.lora.r}_batch${trainer.batch_size}
use_fold: 0

retrieval_model:
  name: nvidia/NV-Embed-v2
  lora:
    r: 128
    lora_alpha: 512

max_candidates: 50

trainer:
  epoch: 20
  batch_size: 2
  gradient_accumulation_steps: 16
  gradient_checkpointing: false  # nvidia-emb-v2は対応していないらしい
