# @package _global_
run_name: run6_dunzhang-stella_en_1.5B_v5_epoch${trainer.epoch}_top${max_candidates}_alpha${retrieval_model.lora.lora_alpha}
use_fold: 0

retrieval_model:
  name: dunzhang/stella_en_1.5B_v5
  names:
    - ${path.model_dir}/${exp_name}/${run_name}
  lora:
    r: 64
    lora_alpha: 256

max_candidates: 50

trainer:
  epoch: 20
  batch_size: 64
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
