# @package _global_
run_name: sub0
phase: test
max_candidates: 25  # アンサンブル用に少し大きめに
retrieval_model:
  base_name: Qwen/Qwen2.5-32B-Instruct
  pretrained_path: ${path.model_dir}/exp053/run0
  use_lora: true
  is_quantized: true
  use_sentence_transformers: false
  batch_size: 4
  lora:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05
    task_type: DEFAULT

ensemble:
  paths:
    - ${path.output_dir}/${exp_name}/${run_name}
  weights:
    - 1

llm_model:
  # name: KirillR/QwQ-32B-Preview-AWQ
  name: Qwen/Qwen2.5-32B-Instruct-AWQ
  pretrained_path: ${path.output_dir}/${exp_name}/run1
  use: true
  predict_type: top1

vllm:
  sampling:
    max_tokens: 1