# @package _global_
run_name: run3
notes: kddの再現
use_fold: 0

negative_size: 2
use_mask_pad_token: true
retrieval_model:
  name: dunzhang/stella_en_1.5B_v5
  use_lora: true
  is_quantized: false
  use_sentence_transformers: false
  lora:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05
    task_type: FEATURE_EXTRACTION

trainer:
  batch_size: 64
  learning_rate: 1e-4
  weight_decay: 0.01
  num_warmup_steps: 100
