# @package _global_
run_name: sub0
phase: test
max_candidates: 30  # アンサンブル用に少し大きめに
retrieval_model:
  base_name: Qwen/Qwen2.5-32B-Instruct-AWQ
  pretrained_path: ${path.model_dir}/exp050/run0
  use_lora: true
  is_quantized: false
  use_sentence_transformers: false
  batch_size: 4
  lora:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05
    task_type: DEFAULT
