# @package _global_
run_name: run0
notes: 2nd stage max_candidates=10
use_fold: 0

feature_version: ${exp_name}/run0
negative_size: 1
use_mask_pad_token: true
max_candidates: 10
retrieval_model:
  base_name: Qwen/Qwen2.5-32B-Instruct
  pretrained_path: ${path.output_dir}/exp053/run0
  use_lora: true
  is_quantized: true
  use_sentence_transformers: false

trainer:
  epoch: 1
  batch_size: 64
  learning_rate: 1e-4
  weight_decay: 0.01
