# @package _global_
run_name: run2
notes: 2nd stage max_candidates=10 negative_size=3
use_fold: 0

feature_version: ${exp_name}/run0
negative_size: 3
use_mask_pad_token: true
max_candidates: 10
retrieval_model:
  base_name: Qwen/Qwen2.5-32B-Instruct
  pretrained_path: ${path.output_dir}/exp053/run0
  use_lora: true
  is_quantized: true
  use_sentence_transformers: false

trainer:
  epoch: 1
  batch_size: 32
  learning_rate: 1e-5
  lr_scheduler_type: constant
  weight_decay: 0.01
  save_steps: 0.5  # training_step全体の何%ごとに保存するか
  logging_steps: 0.5  # training_step全体の何%ごとにログを出力するか
  eval_steps: 0.5  # training_step全体の何%ごとに評価するか