# @package _global_
run_name: dunzhang-stella_en_400M_v5_fold${use_fold}
use_fold: 0


retrieval_model:
  name: dunzhang/stella_en_400M_v5

trainer:
  epoch: 2
  batch_size: 16
  gradient_accumulation_steps: 32  # 128 // batch_size
  gradient_checkpointing: true
