# @package _global_
run_name: run0

reranker_model:
  name: microsoft/deberta-v3-xsmall  # ここを変える場合data_processorを再実行する

trainer:
  batch_size: 64
  gradient_accumulation_steps: 8   # 128 // batch_size
