# @package _global_
run_name: run4
notes: "deberta reranker deberta base"
reranker_model:
  name: microsoft/deberta-v3-base  # ここを変える場合data_processorを再実行する

trainer:
  batch_size: 64
  gradient_accumulation_steps: 1   # 128 // batch_size
