# @package _global_
run_name: run6
notes: "deberta reranker batch size小さくする"
reranker_model:
  name: microsoft/deberta-v3-xsmall  # ここを変える場合data_processorを再実行する

trainer:
  batch_size: 32
  gradient_accumulation_steps: 1   # 128 // batch_size
