# @package _global_
run_name: run1
notes: exp050のbestの条件。ただしdatasetのunseen_rateが変わっている。
use_fold: 0

feature_version: ${exp_name}/run0
negative_size: 2
use_mask_pad_token: true
retrieval_model:
  base_name: Qwen/Qwen2.5-14B-Instruct
  use_lora: true
  is_quantized: true
  use_sentence_transformers: false
  lora:
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05
    task_type: FEATURE_EXTRACTION

trainer:
  epoch: 5
  batch_size: 16
  learning_rate: 1e-4
  weight_decay: 0.01
