# @package _global_
run_name: run0
use_fold: 0

retrieval_model:
  name: dunzhang/stella_en_1.5B_v5
  use_lora: true

trainer:
  epoch: 1
  batch_size: 1
  gradient_accumulation_steps: 16
  gradient_checkpointing: true
