# @package _global_
run_name: run15
notes: "bestであるnegativesize=1, max_candidates=100,lr=5e-5(run7)でnvidiaモデル"
use_fold: 0

retrieval_model:
  name: nvidia/NV-Embed-v2
  use_lora: true

negative_size: 1
max_candidates: 100  # 1つの学習データに紐づける負例の候補数

trainer:
  epoch: 5
  batch_size: 2
  gradient_accumulation_steps: 32
  gradient_checkpointing: false
  learning_rate: 5e-5
