# @package _global_
run_name: run4
notes: "batch size=32"
use_fold: 0

retrieval_model:
  name: dunzhang/stella_en_1.5B_v5
  use_lora: true

negative_size: 10
trainer:
  epoch: 10
  batch_size: 32
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  learning_rate: 8e-6
